spring:
  application:
    name: glucobite
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:1h}
